#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Cltt', '1.0');

try {
    $pdo = new PDO('sqlite:' . dirname(__FILE__) . '/db.sqlite') or die("Can't open the database Captain.");
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS projects(
            id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
            name TEXT
        )"
    );
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS entries(
            id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
            project_id INTEGER,
            start_time INTEGER,
            stop_time INTEGER,
            session_length INTEGER
        )"
    );
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS comments(
            id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
            entry_id INTEGER NOT NULL,
            comment TEXT,
            timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
        )"
    );
} catch(Exception $exception) {
    echo "Error connecting to the database\n";
    echo "Message: " . $exception->getMessage() . "\n";
    if(!extension_loaded('sqlite3')) {
        echo "Looks like php-sqlite3 extension isn't available.\n";
    }

    exit(1);
}

$dbAdapter = new Cltt\DatabaseAdapter($pdo);

$app->add(new Cltt\AddComment($dbAdapter));
$app->add(new Cltt\AddTime($dbAdapter));
$app->add(new Cltt\NewProject($dbAdapter));
$app->add(new Cltt\ArchiveProject($dbAdapter));
$app->add(new Cltt\RestoreProject($dbAdapter));
$app->add(new Cltt\EditTime($dbAdapter));
$app->add(new Cltt\DeleteTime($dbAdapter));
$app->add(new Cltt\ExportEntries($dbAdapter));
$app->add(new Cltt\RunningTimers($dbAdapter));
$app->add(new Cltt\ShowDay($dbAdapter));
$app->add(new Cltt\ShowProjects($dbAdapter));
$app->add(new Cltt\ShowTimes($dbAdapter));
$app->add(new Cltt\ShowWeek($dbAdapter));
$app->add(new Cltt\StartProject($dbAdapter));
$app->add(new Cltt\StopProject($dbAdapter));

$app->run();