#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Project App', '1.0');

try
{
    $pdo = new PDO('sqlite:' . dirname(__FILE__) . '/db.sqlite') or die("Can't open the database Captain.");
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS projects(
            id INTEGER PRIMARY KEY,
            name TEXT
        )"
    );
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS entries(
            id INTEGER PRIMARY KEY,
            project_id INTEGER,
            start_time TEXT,
            stop_time TEXT
        )"
    );
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS comments(
            id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
            entry_id INTEGER NOT NULL,
            comment TEXT,
            timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
        )"
    );
}
catch(Exception $exception)
{
    echo "Could not connect to the database";
    exit(1);
}

$dbAdapter = new Acme\DatabaseAdapter($pdo);

$app->add(new Acme\AddProject($dbAdapter));
$app->add(new Acme\AddComment($dbAdapter));
$app->add(new Acme\ArchiveProject($dbAdapter));
$app->add(new Acme\EditTime($dbAdapter));
$app->add(new Acme\RunningTimers($dbAdapter));
$app->add(new Acme\ShowProjects($dbAdapter));
$app->add(new Acme\ShowTimes($dbAdapter));
$app->add(new Acme\ShowWeek($dbAdapter));
$app->add(new Acme\StartProject($dbAdapter));
$app->add(new Acme\StopProject($dbAdapter));

$app->run();