#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Project App', '1.0');

try
{
    $pdo = new PDO('sqlite:' . dirname(__FILE__) . '/db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch(Exception $exception)
{
    echo "Could not connect to the database";
    exit(1);
}

$dbAdapter = new Acme\DatabaseAdapter($pdo);

$app->add(new Acme\ShowWeek($dbAdapter));
$app->add(new Acme\ShowProjects($dbAdapter));
$app->add(new Acme\AddProject($dbAdapter));
$app->add(new Acme\ArchiveProject($dbAdapter));
$app->add(new Acme\StartProject($dbAdapter));
$app->add(new Acme\StopProject($dbAdapter));
$app->add(new Acme\ShowTimes($dbAdapter));
$app->add(new Acme\RunningTimers($dbAdapter));

$app->run();